apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: if-not-present-image-pull-policy
  annotations:
    policies.kyverno.io/title: if-not-present-image Pull Policy
    policies.kyverno.io/category: Best Practices
    policies.kyverno.io/severity: medium
    policies.kyverno.io/subject: Pod
    policies.kyverno.io/description: >-
      Image pull policy should be set to 'IfNotPresent' to optimize bandwidth and improve deployment speed 
      by avoiding unnecessary image downloads.
spec:
  validationFailureAction: enforce
  rules:
  - name: always-pull-images
    match:
      any:
      - resources:
          kinds:
          - Pod
    mutate:
      patchStrategicMerge:
        spec:
          containers:
          - (name): "?*"
            imagePullPolicy: IfNotPresent